wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.11.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.7
    t:
      1:
      - 1
      - 5
      4: 3.8.7
      5: 0.11.0
      8:
      - 3
      - 5
